=== mrdekk/autumnframework/trunk/doc/Design/autumn.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSpy v2005 rel. 3 U (http://www.altova.com) by  () -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xs:element name="autumn">
		<xs:annotation>
			<xs:documentation>AutumnFramework's root element</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="library" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="library">
		<xs:annotation>
			<xs:documentation>Dynamic library or Local library</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:all>
				<xs:element name="beans">
					<xs:complexType>
						<xs:sequence>
							<xs:element ref="bean" maxOccurs="unbounded"/>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="types" minOccurs="0">
					<xs:complexType>
						<xs:sequence>
							<xs:element ref="bean" minOccurs="0" maxOccurs="unbounded"/>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:all>
			<xs:attribute name="name" type="xs:string"/>
			<xs:attribute name="path" type="xs:string" use="required"/>
			<xs:attribute name="namespace" type="xs:string">
				<xs:annotation>
					<xs:documentation>namespace is useless now.</xs:documentation>
				</xs:annotation>
			</xs:attribute>
		</xs:complexType>
	</xs:element>
	<xs:element name="bean">
		<xs:annotation>
			<xs:documentation>A simple bean</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:all>
				<xs:element name="constructor-arg" minOccurs="0">
					<xs:annotation>
						<xs:documentation>Constructor arguments</xs:documentation>
					</xs:annotation>
					<xs:complexType>
						<xs:sequence>
							<xs:element ref="argument" maxOccurs="unbounded"/>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="properties" minOccurs="0">
					<xs:complexType>
						<xs:sequence>
							<xs:element ref="property" maxOccurs="unbounded"/>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="depends-on" minOccurs="0">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="bean-name" type="xs:string" maxOccurs="unbounded">
								<xs:annotation>
									<xs:documentation>bean-name must not be empty</xs:documentation>
								</xs:annotation>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:all>
			<xs:attribute name="name" type="xs:string"/>
			<xs:attribute name="class" type="xs:string" use="required"/>
			<xs:attribute name="singleton" type="xs:boolean">
				<xs:annotation>
					<xs:documentation>A bean is not a singleton in default</xs:documentation>
				</xs:annotation>
			</xs:attribute>
			<xs:attribute name="factory-bean" type="xs:string"/>
			<xs:attribute name="factory-method">
				<xs:annotation>
					<xs:documentation>The name of a factory method to use to create this object</xs:documentation>
				</xs:annotation>
			</xs:attribute>
			<xs:attribute name="init-method"/>
			<xs:attribute name="destroy-method"/>
			<xs:attribute name="delete-method"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="property" type="propertyType"/>
	<xs:element name="argument">
		<xs:complexType>
			<xs:choice>
				<xs:element name="value" maxOccurs="unbounded">
					<xs:annotation>
						<xs:documentation>If value is empty, it is empty string</xs:documentation>
					</xs:annotation>
				</xs:element>
				<xs:element name="ref">
					<xs:complexType>
						<xs:attribute name="bean"/>
					</xs:complexType>
				</xs:element>
			</xs:choice>
			<xs:attribute name="type"/>
		</xs:complexType>
	</xs:element>
	<xs:complexType name="propertyType">
		<xs:choice>
			<xs:element name="value" maxOccurs="unbounded">
				<xs:annotation>
					<xs:documentation>If value is empty, it is empty string</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="ref">
				<xs:complexType>
					<xs:attribute name="bean"/>
				</xs:complexType>
			</xs:element>
		</xs:choice>
		<xs:attribute name="name" type="xs:string" use="required"/>
		<xs:attribute name="type" type="xs:string" use="optional"/>
	</xs:complexType>
</xs:schema>

=== mrdekk/autumnframework/trunk/src/test/FrameworkTest.xml
<?xml version="1.0" encoding="UTF-8"?>
<autumn xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="E:\Workplace\AutumnFramework\doc\Design\autumn.xsd">
	<library path="./lib/TestDll.dll">
		<beans>
			<!-- BasicTypesBean1 tests property setter -->
			<bean class="BasicTypesBean" name="BasicTypesBean1">
				<properties>
					<property name="Char">
						<value>c</value>
					</property>
					<property name="UChar">
						<value>u</value>
					</property>
					<property name="Short">
						<value>123</value>
					</property>
					<property name="UShort">
						<value>65530</value>
					</property>
					<property name="Int">
						<value>70000</value>
					</property>
					<property name="UInt">
						<value>77777</value>
					</property>
					<property name="Long">
						<value>8000000</value>
					</property>
					<property name="ULong">
						<value>4294967295</value>
					</property>
					<property name="Float">
						<value>1.234567</value>
					</property>
					<property name="Double">
						<value>1.23456789012345</value>
					</property>
					<property name="String">
						<value>hello, String</value>
					</property>
					<property name="CStr">
						<value>hello, CStr</value>
					</property>
					<property name="UCStr">
						<value>hello, UCStr</value>
					</property>
				</properties>
			</bean>
			
			<!-- BasicTypesBean2 tests constructor -->
			<bean class="BasicTypesBean" name="BasicTypesBean2">
				<constructor-arg>
					<argument  name="Char" type="char">
						<value>c</value>
					</argument>
					<argument name="UChar" type="unsigned char">
						<value>u</value>
					</argument>
					<argument name="Short" type="short">
						<value>123</value>
					</argument>
					<argument name="UShort" type="unsigned short">
						<value>65530</value>
					</argument>
					<argument name="Int" type="int">
						<value>70000</value>
					</argument>
					<argument name="UInt" type="unsigned int">
						<value>77777</value>
					</argument>
					<argument name="Long" type="long">
						<value>8000000</value>
					</argument>
					<argument name="ULong" type="unsigned long">
						<value>4294967295</value>
					</argument>
					<argument name="Float" type="float">
						<value>1.234567</value>
					</argument>
					<argument name="Double" type="double">
						<value>1.23456789012345</value>
					</argument>
					<argument name="String" type="string">
						<value>hello, String</value>
					</argument>
					<argument name="CStr" type="char*">
						<value>hello, CStr</value>
					</argument>
					<argument name="UCStr" type="unsigned char*">
						<value>hello, UCStr</value>
					</argument>
				</constructor-arg>
			</bean>
			
			<!-- BasicTypesBean3 tests pointer type -->
			<bean class="BasicTypesBean" name="BasicTypesBean3">
				<properties>
					<property name="IntP">
						<value>70000</value>
					</property>
					<property name="CStrP">
						<value>hello, CStr</value>
					</property>
				</properties>
			</bean>

			<!-- BeanTypeBean test bean injection -->
			<bean class="BeanTypeBean" name="BeanTypeBean1">
				<properties>
					<property name="Int">
						<value>BasicTypesBean3</value>
					</property>
					<property name="CStr">
						<value>BasicTypesBean4</value>
					</property>
				</properties>
			</bean>
			<bean class="BeanTypeBean" name="BeanTypeBean2">
				<constructor-arg>
					<argument name="arg1" type="BasicTypesBean*">
						<value>BasicTypesBean3</value>
					</argument>
				</constructor-arg>
			</bean>
			<bean class="BasicTypesBean" name="BasicTypesBean4">
				<properties>
					<property name="CStr">
						<value>hello, CStr for bean4</value>
					</property>
				</properties>
			</bean>
			
			<!-- BeanTypeBean3 test bean injection from another library -->
			<bean class="BeanTypeBean" name="BeanTypeBean5">
				<constructor-arg>
					<argument name="arg1" type="BasicTypesBean*">
						<value>BasicTypesBean2-1</value>
					</argument>
				</constructor-arg>
			</bean>

			<!-- SingletonBean test singleton property -->
			<bean class="SingletonBean" name="NotSingleton1">
				<properties>
					<property name="String">
						<value>Not Singleton</value>
					</property>
				</properties>
			</bean>
			<bean class="SingletonBean" name="SingletonBean1" singleton="true">
				<properties>
					<property name="String">
						<value>Singleton Bean</value>
					</property>
				</properties>
			</bean>
			
			<!-- InitDestBean test destroyable and initializable property -->
			<bean class="InitDestBean" name="InitDestBean1" destroyable="true" initializable="true">
				<constructor-arg>
					<argument name="arg1" type="SingletonBean*">
						<value>SingletonBean1</value>
					</argument>
				</constructor-arg>
			</bean>
			
			<!-- The fllowing is useless, self-managed property can't be used-->
			<!-- SelfManagedBean test self-managed property -->
			<!--
			<bean class="SelfManagedBean" name="SelfManagedBean1">
					<constructor-arg>
						<argument name="arg1" type="SingletonBean*" autumn-manage="false">
							<value>NotSingleton1</value>
						</argument>
					</constructor-arg>
					<properties>
						<property name="CStr" type="char*" autumn-manage="false">
							<value>Hello, SelfManagedBean</value>
						</property>
					</properties>
			</bean>
			-->

			<!-- MyTypeBean test customized types -->
			<bean class="MyTypeBean" name="MyTypeBean1">
				<properties>
					<property name="MyData">
						<value>100</value>
						<value>Hi, MyData!</value>
					</property>
				</properties>
			</bean>
			
			<!-- test factory -->
			<bean class="Factory1" name="Factory11" singleton="true" />
			<bean class="Factory2" name="Factory22" singleton="true" />
			<bean class="IProductA" name="ProductA1">
				<constructor-arg>
					<argument name="arg1" type="Factory1">
						<value>Factory11</value>
					</argument>
					<argument name="arg2" type="string">
						<value>name_A1</value>
					</argument>
				</constructor-arg>
			</bean>
			<bean class="IProductB" name="ProductB1">
				<constructor-arg>
					<argument name="arg1" type="Factory1">
						<value>Factory11</value>
					</argument>
					<argument name="arg2" type="string">
						<value>name_B1</value>
					</argument>
				</constructor-arg>
			</bean>
			<bean class="IProductC" name="ProductC1">
				<constructor-arg>
					<argument name="arg1" type="Factory1">
						<value>Factory11</value>
					</argument>
				</constructor-arg>
				<properties>
					<property name="Name">
						<value>name_C1</value>
					</property>
				</properties>
			</bean>
			<bean class="IProductA" name="ProductA2">
				<constructor-arg>
					<argument name="arg1" type="Factory2">
						<value>Factory22</value>
					</argument>
					<argument name="arg2" type="string">
						<value>name_A2</value>
					</argument>
				</constructor-arg>
			</bean>
			<bean class="IProductB" name="ProductB2" factory-bean="Factory22">
				<constructor-arg>
					<argument name="arg2" type="string">
						<value>name_B2</value>
					</argument>
				</constructor-arg>
			</bean>
			
			<!-- Test static factory method -->
			<bean class="ProductA_M" name="ProductAM">
				<constructor-arg>
					<argument name="arg1" type="string">
						<value>name_AM</value>
					</argument>
				</constructor-arg>
			</bean>
			<bean class="ProductB_M" name="ProductBM" />
			
		</beans>
		<types>
			<type class="MyBasicType" name="MyData" />
		</types>
	</library>
	
	<library path="./lib/TestDll2.dll">
		<beans>
			<bean class="BasicTypesBean" name="BasicTypesBean2-1">
				<properties>
					<property name="IntP">
						<value>70021</value>
					</property>
					<property name="CStrP">
						<value>hello, CStr2-1</value>
					</property>
				</properties>
			</bean>
		</beans>
	</library>
	
	<library path="local">
		<beans>
			<bean class="LocalBean" name="LocalBean1">
				<properties>
					<property name="Int">
						<value>BasicTypesBean3</value>
					</property>
					<property name="CStr">
						<value>hello, Local Bean</value>
					</property>
				</properties>
			</bean>
			
			<!-- Configure autumn framework logger bean -->
			<bean class="FileLogger" name="AutumnFrameworkLog" singleton="true">
				<constructor-arg>
					<argument name="arg1" type="string">
						<value>AutumnApp.log</value>
					</argument>
					<argument name="arg2" type="int">
						<value>0</value>
					</argument>
				</constructor-arg>
			</bean>
		</beans>
	</library>
	
</autumn>

=== mrdekk/autumnframework/trunk/src/UnitTest/AutumnUnitTest.xml
<?xml version="1.0" encoding="UTF-8"?>
<autumn xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="E:\Workplace\AutumnFramework\doc\Design\autumn.xsd">
	<library path="../lib/UnitTestDll_D.dll">
		<beans>
			<!-- BasicTypesBean1 tests property setter -->
			<bean class="BasicTypesBean" name="BasicTypesBean1">
				<properties>
					<property name="Char" type="char">
						<value>c</value>
					</property>
					<property name="UChar" type="unsigned char">
						<value>u</value>
					</property>
					<property name="Short" type="short">
						<value>123</value>
					</property>
					<property name="UShort" type="unsigned short">
						<value>65530</value>
					</property>
					<property name="Int" type="int">
						<value>70000</value>
					</property>
					<property name="UInt" type="unsigned int">
						<value>77777</value>
					</property>
					<property name="Long" type="long">
						<value>8000000</value>
					</property>
					<property name="ULong" type="unsigned long">
						<value>4294967295</value>
					</property>
					<property name="Float" type="float">
						<value>1.234567</value>
					</property>
					<property name="Double" type="double">
						<value>1.23456789012345</value>
					</property>
					<property name="String" type="string">
						<value>hello, String</value>
					</property>
					<property name="CStr" type="char*">
						<value>hello, CStr</value>
					</property>
					<property name="UCStr" type="unsigned char*">
						<value>hello, UCStr</value>
					</property>
				</properties>
			</bean>
			
			<!-- BasicTypesBean2 tests constructor -->
			<bean class="BasicTypesBean" name="BasicTypesBean2">
				<constructor-arg>
					<argument  name="Char" type="char">
						<value>c</value>
					</argument>
					<argument name="UChar" type="unsigned char">
						<value>u</value>
					</argument>
					<argument name="Short" type="short">
						<value>123</value>
					</argument>
					<argument name="UShort" type="unsigned short">
						<value>65530</value>
					</argument>
					<argument name="Int" type="int">
						<value>70000</value>
					</argument>
					<argument name="UInt" type="unsigned int">
						<value>77777</value>
					</argument>
					<argument name="Long" type="long">
						<value>8000000</value>
					</argument>
					<argument name="ULong" type="unsigned long">
						<value>4294967295</value>
					</argument>
					<argument name="Float" type="float">
						<value>1.234567</value>
					</argument>
					<argument name="Double" type="double">
						<value>1.23456789012345</value>
					</argument>
					<argument name="String" type="string">
						<value>hello, String</value>
					</argument>
					<argument name="CStr" type="char*">
						<value>hello, CStr</value>
					</argument>
					<argument name="UCStr" type="unsigned char*">
						<value>hello, UCStr</value>
					</argument>
				</constructor-arg>
			</bean>
			
			<!-- BasicTypesBean3 tests pointer type -->
			<bean class="BasicTypesBean" name="BasicTypesBean3">
				<properties>
					<property name="Int" type="int*">
						<value>70000</value>
					</property>
					<property name="CStr" type="char**">
						<value>hello, CStr</value>
					</property>
				</properties>
			</bean>

			<!-- BeanTypeBean test bean injection -->
			<bean class="BeanTypeBean" name="BeanTypeBean1">
				<properties>
					<property name="Int" type="BasicTypesBean*">
						<value>BasicTypesBean3</value>
					</property>
					<property name="CStr" type="BasicTypesBean">
						<value>BasicTypesBean4</value>
					</property>
				</properties>
			</bean>
			<bean class="BeanTypeBean" name="BeanTypeBean2">
				<constructor-arg>
					<argument name="arg1" type="BasicTypesBean*">
						<value>BasicTypesBean3</value>
					</argument>
				</constructor-arg>
			</bean>
			<bean class="BasicTypesBean" name="BasicTypesBean4">
				<properties>
					<property name="CStr" type="char*">
						<value>hello, CStr for bean4</value>
					</property>
				</properties>
			</bean>
			
			<!-- BeanTypeBean3 test bean injection from another library -->
			<bean class="BeanTypeBean" name="BeanTypeBean5">
				<constructor-arg>
					<argument name="arg1" type="BasicTypesBean*">
						<value>BasicTypesBean2-1</value>
					</argument>
				</constructor-arg>
			</bean>

			<!-- SingletonBean test singleton property -->
			<bean class="SingletonBean" name="NotSingleton1">
				<properties>
					<property name="String" type="string">
						<value>Not Singleton</value>
					</property>
				</properties>
			</bean>
			<bean class="SingletonBean" name="SingletonBean1" singleton="true">
				<properties>
					<property name="String" type="string">
						<value>Singleton Bean</value>
					</property>
				</properties>
			</bean>
			
			<!-- InitDestBean test destroyable and initializable property -->
			<bean class="InitDestBean" name="InitDestBean1" destroyable="true" initializable="true">
				<constructor-arg>
					<argument name="arg1" type="SingletonBean*">
						<value>SingletonBean1</value>
					</argument>
				</constructor-arg>
			</bean>
			
			<!-- The fllowing is useless, self-managed property can't be used-->
			<!-- SelfManagedBean test self-managed property -->
			<!--
			<bean class="SelfManagedBean" name="SelfManagedBean1">
					<constructor-arg>
						<argument name="arg1" type="SingletonBean*" autumn-manage="false">
							<value>NotSingleton1</value>
						</argument>
					</constructor-arg>
					<properties>
						<property name="CStr" type="char*" autumn-manage="false">
							<value>Hello, SelfManagedBean</value>
						</property>
					</properties>
			</bean>
			-->

			<!-- MyTypeBean test customized types -->
			<bean class="MyTypeBean" name="MyTypeBean1">
				<properties>
					<property name="MyData" type="MyData*">
						<value>100</value>
						<value>Hi, MyData!</value>
					</property>
				</properties>
			</bean>
		</beans>
		<types>
			<type class="MyBasicType" name="MyData" />
		</types>
	</library>
	
	<library path="../lib/UnitTestDll2_D.dll">
		<beans>
			<bean class="BasicTypesBean" name="BasicTypesBean2-1">
				<properties>
					<property name="Int" type="int*">
						<value>70021</value>
					</property>
					<property name="CStr" type="char**">
						<value>hello, CStr2-1</value>
					</property>
				</properties>
			</bean>
		</beans>
	</library>
	
	<library path="local">
		<beans>
			<bean class="LocalBean" name="LocalBean1">
				<properties>
					<property name="Int" type="BasicTypesBean*" inject-type="IBasicTypesBean*">
						<value>BasicTypesBean3</value>
					</property>
					<property name="CStr" type="char*">
						<value>hello, Local Bean</value>
					</property>
				</properties>
			</bean>
		</beans>
	</library>
	
</autumn>
